class Book < ApplicationRecord
  # This was automatically generated by the migration command:
  # rails g model Book title author:belongs_to
  # It helps Rails create the association *in the Rails app*
  # Open app/models/author.rb
  belongs_to :author
end
